### ISSUE TITLE
2fa process (question)

### ISSUE THREAD

**Issue by djengineerllc** [PrometheanInfoSec/Lockdown#1]
Just curious,  how does this work with 2fa?

I'm guessing I'd setup a one-time password so I wouldn't have to use 2fa in the script.  Then it would change the password and 2fa would still be enabled on the accounts.

I'm going to check this out.  Thanks PrometheanInfoSec!

**Comment by djengineerllc** [comment]
Hmm, just realized I need a GUI linux to run this on.
I installed splinter and firefox, but it still doesn't work w/o X11.

Am I correct to assume this?  I'm getting the following error:
"X11 connection rejected because of wrong authentication."

**Comment by PrometheanInfoSec** [comment]
Yes, what you just described for 2fa should work.

Sorry about the need for a gui, it should work cross platform though.

The gui Firefox is necessary to bypass bot detection.  If I get some time
one thing I would love is to find a way to work without it.

**Comment by djengineerllc** [comment]
ah, ok!  Thanks!  I'll try to set this up on my laptop instead to see if it'll work.

**Comment by PrometheanInfoSec** [comment]
Do let me know if you need anything.  Open up issues/feature requests on
github and I'll try to get to them when I have a moment.
